"""Remove email_status and is_email_verified from users

Revision ID: 39b87c583e61
Revises: 6bfa6bcff650
Create Date: 2026-02-07 09:14:11.826590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39b87c583e61"
down_revision: Union[str, Sequence[str], None] = "6bfa6bcff650"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_status")
    op.drop_column("users", "is_email_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_email_verified", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_status", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
