"""Add Payment and PaymentItem tables

Revision ID: cd49c9df4aae
Revises: 644b4281bd2a
Create Date: 2026-02-05 14:44:44.487188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd49c9df4aae"
down_revision: Union[str, Sequence[str], None] = "644b4281bd2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
