"""paymentintent

Revision ID: e64b545a0e6c
Revises: 39b87c583e61
Create Date: 2026-02-08 20:26:40.781552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e64b545a0e6c"
down_revision: Union[str, Sequence[str], None] = "39b87c583e61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("payment_intent", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "payment_intent")
    # ### end Alembic commands ###
